// Icon mappings and configurations
import { 
  SiReact, 
  SiNextdotjs, 
  SiTypescript, 
  SiTailwindcss, 
  SiVuedotjs, 
  SiJavascript,
  SiNodedotjs, 
  SiPython, 
  SiPostgresql, 
  SiMongodb,
  SiGit, 
  SiDocker, 
  SiAmazonwebservices, 
  SiVercel, 
  SiFigma,
  SiLinux,
  SiGraphql,
  SiAutodesk,
  SiAnsys,
  SiArduino,
  SiRaspberrypi,
  SiLeetcode
} from 'react-icons/si';

import { 
  Code, 
  Database, 
  Server, 
  Lightbulb, 
  Target, 
  Wrench,
  Settings,
  Cpu,
  Zap,
  BarChart3
} from 'lucide-react';

// Technology logo mapping
export const techLogos: Record<string, React.ComponentType<any>> = {
  // Frontend
  'React': SiReact,
  'Next.js': SiNextdotjs,
  'TypeScript': SiTypescript,
  'Tailwind CSS': SiTailwindcss,
  'Vue.js': SiVuedotjs,
  'JavaScript': SiJavascript,
  
  // Backend
  'Node.js': SiNodedotjs,
  'Python': SiPython,
  'PostgreSQL': SiPostgresql,
  'MongoDB': SiMongodb,
  'GraphQL': SiGraphql,
  
  // Tools & Platforms
  'Git': SiGit,
  'Docker': SiDocker,
  'AWS': SiAmazonwebservices,
  'Vercel': SiVercel,
  'Figma': SiFigma,
  'Linux': SiLinux,
  'LeetCode': SiLeetcode,
  
  // Mechanical Engineering Tools
  'SolidWorks': SiAutodesk,
  'AutoCAD': SiAutodesk,
  'Fusion 360': SiAutodesk,
  'ANSYS': SiAnsys,
  'Arduino': SiArduino,
  'Raspberry Pi': SiRaspberrypi,
  
  // Fallback icons for concepts and other technologies
  'REST APIs': Server,
  'System Design': Settings,
  'Testing': Target,
  'Agile': Lightbulb,
  'DevOps': Settings,
  'UI/UX': Lightbulb,
  'CNC Programming': Cpu,
  '3D Printing': Settings,
  'Quality Control': Target,
  'Lean Manufacturing': BarChart3,
  'FEA': BarChart3,
  'CFD': Zap,
  'Thermal Analysis': Zap,
  'Creo': Wrench,
  'Six Sigma': Target,
  'Cost Estimation': BarChart3,
  'Supply Chain': Settings,
  'Project Management': Target,
  'Thermodynamics': Zap,
  'Energy Systems': Zap,
  'Heat Transfer': Zap,
  'Flow Analysis': Zap,
  'Heat Exchangers': Wrench,
  'LMTD Analysis': BarChart3,
  'Automotive HVAC': Settings,
  'Thermal Design': Zap,
  'Energy Recovery': Zap,
  'Manufacturing': Settings,
  'Process Optimization': Target,
  'Sustainability': Lightbulb,
  'Materials Science': Wrench,
  'Composite Design': Wrench,
  'Testing & Validation': Target,
  'Quality Assurance': Target,
  'Metrology': Target,
  'Automation': Settings,
  'Statistical Analysis': BarChart3,
  'LabVIEW': Code,
  'Robotics': Cpu,
  'Computer Vision': Target,
  'PLC Programming': Code,
  'SCADA': Settings,
  'IoT': Cpu,
  'Control Systems': Settings,
  'Energy Modeling': BarChart3,
  'Prototyping': Wrench,
  'Life Cycle Analysis': BarChart3,
  'Environmental Engineering': Lightbulb,
  'High-Performance Computing': Cpu,
  'Turbomachinery': Wrench,
  'MATLAB': BarChart3,
  'HTML/CSS': Code,
  'API Integration': Server,
  'Data Visualization': BarChart3,
  'Log Analysis': BarChart3,
  'Pygame': Code,
  'AppScript': Code,
  'Pandas': BarChart3,
  'NumPy': BarChart3,
  'Google Sheets API': Database,
  'AES Encryption': Settings,
  'OTP Authentication': Settings,
  'PDF Processing': Code,
  'Web Development': Code,
  'Automation': Settings,
  'Speech Recognition': Lightbulb,
  'Web Scraping': Server,
  'winsdk': Settings,
  'Finite Difference Method': BarChart3,
  'Numerical Modeling': BarChart3,
  'Finite Difference': BarChart3,
  'Matplotlib': BarChart3,
  'Game Development': Code,
  'Object-Oriented Programming': Code,
  'C++': Code,
  'MATLAB': BarChart3,
  'ANSYS Mechanical': SiAnsys,
  'CAD Design': Wrench,
  '3D Modeling': Wrench,
  'ANSYS Fluent': SiAnsys,
  'Structural Analysis': Wrench,
  'HVAC': Settings,
  'Organic Rankine Cycle': Zap,
  'Exergy Analysis': BarChart3,
  'Metal Fabrication': Wrench,
  'Dynamic Modeling': BarChart3,
  'Heat Transfer Simulation': Zap,
  'Mesh Optimization': Settings,
  'Flow Analysis': Zap
};

// Color mapping for specific technologies
export const techColors: Record<string, string> = {
  'React': '#61DAFB',
  'Next.js': '#000000',
  'TypeScript': '#3178C6',
  'Tailwind CSS': '#06B6D4',
  'Vue.js': '#4FC08D',
  'JavaScript': '#F7DF1E',
  'Node.js': '#339933',
  'Python': '#3776AB',
  'PostgreSQL': '#336791',
  'MongoDB': '#47A248',
  'GraphQL': '#E10098',
  'Git': '#F05032',
  'Docker': '#2496ED',
  'AWS': '#FF9900',
  'Vercel': '#000000',
  'Figma': '#F24E1E',
  'Linux': '#FCC624',
  'LeetCode': '#FFA116',
  'SolidWorks': '#FF0000',
  'AutoCAD': '#E51937',
  'Fusion 360': '#FF6600',
  'ANSYS': '#FFB71B',
  'MATLAB': '#0076A8',
  'Arduino': '#00979D',
  'Raspberry Pi': '#A22846'
};